<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;

use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Http;


class PencarianSeeder extends Seeder
{
    public function run()
    {
        // Data Yogyakarta
        DB::table('pencarian')->insert([
            [
                'name' => 'Hotel The Phoenix Yogyakarta',
                'description' => 'Hotel bersejarah dengan fasilitas modern.',
                'location' => 'Yogyakarta',
                'latitude' => -7.7829,
                'longitude' => 110.3671,
                'phone_number' => '0274567890',
                'facilities' => 'Kolam renang, Wi-Fi gratis, Restoran',
                'rating' => 4.7,
                'image_url' => 'https://i.pinimg.com/736x/17/ca/06/17ca06c108252e23ed8f230c894fe736.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'available_from' => Carbon::now()->toDateString(),
                'available_to' => Carbon::now()->addDays(30)->toDateString(),
            ],
            [
                'name' => 'Hyatt Regency Yogyakarta',
                'description' => 'Resor luas dengan lapangan golf dan pemandangan hijau.',
                'location' => 'Yogyakarta',
                'latitude' => -7.7470,
                'longitude' => 110.3617,
                'phone_number' => '0274888888',
                'facilities' => 'Lapangan golf, Kolam renang, Spa',
                'rating' => 4.8,
                'image_url' => 'https://i.pinimg.com/236x/a7/32/c8/a732c86f8d67590f9a228d527b2ad136.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'available_from' => Carbon::now()->toDateString(),
                'available_to' => Carbon::now()->addDays(30)->toDateString(),
            ],
            [
                'name' => 'Royal Ambarrukmo Yogyakarta',
                'description' => 'Hotel mewah dengan sentuhan budaya Jawa.',
                'location' => 'Yogyakarta',
                'latitude' => -7.7823,
                'longitude' => 110.4086,
                'phone_number' => '0274581234',
                'facilities' => 'Pusat kebugaran, Kolam renang, Restoran',
                'rating' => 4.9,
                'image_url' => 'https://i.pinimg.com/236x/ba/6b/c9/ba6bc96d0e0f2c5a8e3ea99cc8c17f14.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'available_from' => Carbon::now()->toDateString(),
                'available_to' => Carbon::now()->addDays(30)->toDateString(),
            ],
            [
                'name' => 'Melia Purosani Yogyakarta',
                'description' => 'Hotel bintang lima dengan fasilitas lengkap.',
                'location' => 'Yogyakarta',
                'latitude' => -7.7995,
                'longitude' => 110.3644,
                'phone_number' => '0274593210',
                'facilities' => 'Spa, Kolam renang, Restoran',
                'rating' => 4.6,
                'image_url' => 'https://i.pinimg.com/236x/4e/56/ef/4e56efea865e327c7b55d6636bb14550.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'available_from' => Carbon::now()->toDateString(),
                'available_to' => Carbon::now()->addDays(30)->toDateString(),
            ],
            [
                'name' => 'Amaris Hotel Malioboro',
                'description' => 'Hotel budget dekat Malioboro.',
                'location' => 'Yogyakarta',
                'latitude' => -7.7924,
                'longitude' => 110.3653,
                'phone_number' => '02744567890',
                'facilities' => 'Wi-Fi gratis, Restoran, Parkir',
                'rating' => 4.3,
                'image_url' => 'https://i.pinimg.com/236x/2b/39/72/2b3972c97c67499c79e77f8f98e2ff23.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'available_from' => Carbon::now()->toDateString(),
                'available_to' => Carbon::now()->addDays(30)->toDateString(),
            ],
            [
                'name' => 'Hotel Tentrem Yogyakarta',
                'description' => 'Hotel mewah dengan fasilitas spa terbaik.',
                'location' => 'Yogyakarta',
                'latitude' => -7.7760,
                'longitude' => 110.3798,
                'phone_number' => '0274887766',
                'facilities' => 'Spa, Kolam renang, Gym',
                'rating' => 4.8,
                'image_url' => 'https://i.pinimg.com/236x/f3/12/67/f31267ff43b2db3b1fd52cd07dd6ef08.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'available_from' => Carbon::now()->toDateString(),
                'available_to' => Carbon::now()->addDays(30)->toDateString(),
            ],
        ]);

        // Data Bali
        DB::table('pencarian')->insert([
            [
                'name' => 'Bali Villa with Garden View',
                'description' => 'Villa indah dengan pemandangan taman tropis.',
                'location' => 'Bali',
                'latitude' => -8.409518,
                'longitude' => 115.188919,
                'phone_number' => '08123456789',
                'facilities' => 'Kolam Renang, WiFi Gratis, Taman',
                'rating' => 4.9,
                'image_url' => 'https://i.pinimg.com/236x/fd/11/a1/fd11a1f831ab9e974495c293d2fbf99.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'available_from' => Carbon::now()->toDateString(),
                'available_to' => Carbon::now()->addDays(30)->toDateString(),
            ],
            [
                'name' => 'Bali Beachfront Resort',
                'description' => 'Resort mewah dengan pemandangan pantai langsung.',
                'location' => 'Bali',
                'latitude' => -8.412345,
                'longitude' => 115.200123,
                'phone_number' => '08129876543',
                'facilities' => 'Pantai Pribadi, Kolam Renang Infinity, Spa',
                'rating' => 4.8,
                'image_url' => 'https://i.pinimg.com/236x/47/89/fd/4789fd021e0f1814d7f31d6260702b86.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'available_from' => Carbon::now()->toDateString(),
                'available_to' => Carbon::now()->addDays(30)->toDateString(),
            ],
            [
                'name' => 'Bali Tropical Resort',
                'description' => 'Resort tropis dengan kamar luas dan pemandangan laut.',
                'location' => 'Bali',
                'latitude' => -8.421234,
                'longitude' => 115.201567,
                'phone_number' => '08134567890',
                'facilities' => 'Kolam Renang, Restoran, Spa',
                'rating' => 4.7,
                'image_url' => 'https://i.pinimg.com/236x/20/63/a2/2063a2e8831471b055ac707f60fa22c.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'available_from' => Carbon::now()->toDateString(),
                'available_to' => Carbon::now()->addDays(30)->toDateString(),
            ],
            [
                'name' => 'Ubud Luxury Villa',
                'description' => 'Villa nyaman di Ubud dengan suasana tenang.',
                'location' => 'Bali',
                'latitude' => -8.500123,
                'longitude' => 115.273456,
                'phone_number' => '08127894567',
                'facilities' => 'Kolam Renang, WiFi Gratis, Sarapan',
                'rating' => 4.9,
                'image_url' => 'https://i.pinimg.com/236x/60/59/aa/6059aa39b6978d0b04903dcaf7c63111.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'available_from' => Carbon::now()->toDateString(),
                'available_to' => Carbon::now()->addDays(30)->toDateString(),
            ],
            [
                'name' => 'Bali Private Pool Villa',
                'description' => 'Villa eksklusif dengan kolam renang pribadi.',
                'location' => 'Bali',
                'latitude' => -8.409900,
                'longitude' => 115.222345,
                'phone_number' => '08124567890',
                'facilities' => 'Kolam Renang Pribadi, AC, Dapur Lengkap',
                'rating' => 4.8,
                'image_url' => 'https://i.pinimg.com/236x/8b/07/ee/8b07ee3caeba65a7075bbf1840c18e7.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'available_from' => Carbon::now()->toDateString(),
                'available_to' => Carbon::now()->addDays(30)->toDateString(),
            ],
            [
                'name' => 'Nusa Dua Water Villa',
                'description' => 'Villa indah dengan akses langsung ke air.',
                'location' => 'Bali',
                'latitude' => -8.800234,
                'longitude' => 115.225678,
                'phone_number' => '08125678901',
                'facilities' => 'Kolam Renang, Akses Air, Sarapan',
                'rating' => 4.8,
                'image_url' => 'https://i.pinimg.com/736x/7a/86/2e/7a8622e9ba33beb69ecd4049abb7173.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'available_from' => Carbon::now()->toDateString(),
                'available_to' => Carbon::now()->addDays(30)->toDateString(),
            ],
        ]);

        // Data Labuan Bajo
        DB::table('pencarian')->insert([
            [
                'name' => 'Labuan Bajo Beach Resort',
                'description' => 'Resor pantai dengan pemandangan Laut Flores.',
                'location' => 'Labuan Bajo',
                'latitude' => -8.4864,
                'longitude' => 119.8870,
                'phone_number' => '08123456789',
                'facilities' => 'Pantai Pribadi, Kolam Renang, Restoran',
                'rating' => 4.7,
                'image_url' => 'https://i.pinimg.com/236x/ab/72/ff/ab72ff2c8bff54f6c1b6800b21ea5ac7.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'available_from' => Carbon::now()->toDateString(),
                'available_to' => Carbon::now()->addDays(30)->toDateString(),
            ],
            [
                'name' => 'Labuan Bajo Luxury Villas',
                'description' => 'Vila mewah dengan kolam renang pribadi di Labuan Bajo.',
                'location' => 'Labuan Bajo',
                'latitude' => -8.4721,
                'longitude' => 119.8872,
                'phone_number' => '08129876543',
                'facilities' => 'Kolam Renang Pribadi, Spa, Taman',
                'rating' => 4.9,
                'image_url' => 'https://i.pinimg.com/236x/35/4b/7d/354b7d8c9a3f2d241ef4b31ed5732069.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'available_from' => Carbon::now()->toDateString(),
                'available_to' => Carbon::now()->addDays(30)->toDateString(),
            ],
            [
                'name' => 'Komodo Dive Resort',
                'description' => 'Resor menyelam dengan akses langsung ke Pulau Komodo.',
                'location' => 'Labuan Bajo',
                'latitude' => -8.4315,
                'longitude' => 119.8907,
                'phone_number' => '08134567890',
                'facilities' => 'Menyelam, Kolam Renang, Restoran',
                'rating' => 4.8,
                'image_url' => 'https://i.pinimg.com/236x/da/12/9f/da129fd5c88be2b803c09a660c848eb6.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'available_from' => Carbon::now()->toDateString(),
                'available_to' => Carbon::now()->addDays(30)->toDateString(),
            ],
            [
                'name' => 'Labuan Bajo Eco Resort',
                'description' => 'Resor ramah lingkungan di Labuan Bajo dengan pemandangan alam.',
                'location' => 'Labuan Bajo',
                'latitude' => -8.4753,
                'longitude' => 119.8859,
                'phone_number' => '08127654321',
                'facilities' => 'Kolam Renang, Ekowisata, Restoran',
                'rating' => 4.6,
                'image_url' => 'https://i.pinimg.com/236x/1f/84/49/1f8449f334e054d54474b433da823839.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'available_from' => Carbon::now()->toDateString(),
                'available_to' => Carbon::now()->addDays(30)->toDateString(),
            ],
            [
                'name' => 'Labuan Bajo Sunset View',
                'description' => 'Vila dengan pemandangan matahari terbenam yang indah.',
                'location' => 'Labuan Bajo',
                'latitude' => -8.4936,
                'longitude' => 119.8982,
                'phone_number' => '08125678901',
                'facilities' => 'Pemandangan Laut, Kolam Renang, Restoran',
                'rating' => 4.8,
                'image_url' => 'https://i.pinimg.com/236x/8d/2c/3a/8d2c3ac50fa0ac81b688438a64a11d1e.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'available_from' => Carbon::now()->toDateString(),
                'available_to' => Carbon::now()->addDays(30)->toDateString(),
            ],
        ]);

// Data Jakarta
DB::table('pencarian')->insert([
    [
        'name' => 'Hotel Mulia Senayan',
        'description' => 'Hotel mewah di pusat kota Jakarta.',
        'location' => 'Jakarta',
        'latitude' => -6.2261,
        'longitude' => 106.7914,
        'phone_number' => '02112345678',
        'facilities' => 'Kolam Renang, Spa, Restoran',
        'rating' => 4.9,
        'image_url' => 'https://i.pinimg.com/236x/15/8a/a6/158aa61706315fa6d5f6b8a519de59f4.jpg',
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
        'available_from' => Carbon::now()->toDateString(),
        'available_to' => Carbon::now()->addDays(30)->toDateString(),
    ],
    [
        'name' => 'Grand Hyatt Jakarta',
        'description' => 'Hotel bintang lima di pusat kota Jakarta.',
        'location' => 'Jakarta',
        'latitude' => -6.1959,
        'longitude' => 106.8221,
        'phone_number' => '02198765432',
        'facilities' => 'Pusat Kebugaran, Kolam Renang, Restoran',
        'rating' => 4.8,
        'image_url' => 'https://i.pinimg.com/236x/9a/53/c8/9a53c892b7c67b94f899cfdf2c83d5f4.jpg',
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
        'available_from' => Carbon::now()->toDateString(),
        'available_to' => Carbon::now()->addDays(30)->toDateString(),
    ],
    [
        'name' => 'The Ritz-Carlton Jakarta',
        'description' => 'Hotel mewah dengan layanan kelas dunia.',
        'location' => 'Jakarta',
        'latitude' => -6.2322,
        'longitude' => 106.8047,
        'phone_number' => '02123456789',
        'facilities' => 'Spa, Kolam Renang, Restoran',
        'rating' => 4.9,
        'image_url' => 'https://i.pinimg.com/236x/d7/55/c3/d755c3ad1cc1bc515b276ce9efb71cfd.jpg',
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
        'available_from' => Carbon::now()->toDateString(),
        'available_to' => Carbon::now()->addDays(30)->toDateString(),
    ],
    [
        'name' => 'Shangri-La Hotel Jakarta',
        'description' => 'Hotel bintang lima dengan fasilitas lengkap.',
        'location' => 'Jakarta',
        'latitude' => -6.2356,
        'longitude' => 106.8225,
        'phone_number' => '0217654321',
        'facilities' => 'Spa, Kolam Renang, Pusat Kebugaran',
        'rating' => 4.8,
        'image_url' => 'https://i.pinimg.com/236x/64/f2/ee/64f2ee1180c8857ffb22cd76743d11e3.jpg',
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
        'available_from' => Carbon::now()->toDateString(),
        'available_to' => Carbon::now()->addDays(30)->toDateString(),
    ],
    [
        'name' => 'Hotel Indonesia Kempinski Jakarta',
        'description' => 'Hotel ikonik di Jakarta dengan pemandangan kota.',
        'location' => 'Jakarta',
        'latitude' => -6.1945,
        'longitude' => 106.8220,
        'phone_number' => '02167890123',
        'facilities' => 'Kolam Renang, Restoran, Spa',
        'rating' => 4.9,
        'image_url' => 'https://i.pinimg.com/236x/1a/15/3d/1a153d4065fbc25f0d0c8a0b1d829fb4.jpg',
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
        'available_from' => Carbon::now()->toDateString(),
        'available_to' => Carbon::now()->addDays(30)->toDateString(),
    ],
    [
        'name' => 'Four Seasons Hotel Jakarta',
        'description' => 'Hotel mewah dengan pemandangan kota Jakarta.',
        'location' => 'Jakarta',
        'latitude' => -6.2312,
        'longitude' => 106.8023,
        'phone_number' => '02198765432',
        'facilities' => 'Kolam Renang, Restoran, Spa',
        'rating' => 4.8,
        'image_url' => 'https://i.pinimg.com/236x/c3/d0/c5/c3d0c5234ff2f9b49d1f0ca72b615abc.jpg',
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
        'available_from' => Carbon::now()->toDateString(),
        'available_to' => Carbon::now()->addDays(30)->toDateString(),

    ],

]);

    }
}
