<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;

use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Http;


class PencarianSeeder extends Seeder
{
    public function run()
    {
        // Data Yogyakarta
        DB::table('pencarian')->insert([
            [
                'name' => 'Hotel The Phoenix Yogyakarta',
                'description' => 'Hotel bersejarah dengan fasilitas modern.',
                'location' => 'Yogyakarta',
                'latitude' => -7.7829,
                'longitude' => 110.3671,
                'phone_number' => '0274567890',
                'facilities' => 'Kolam renang, Wi-Fi gratis, Restoran',
                'rating' => 4.7,
                'image_url' => 'https://i.pinimg.com/736x/17/ca/06/17ca06c108252e23ed8f230c894fe736.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'available_from' => Carbon::now()->toDateString(),
                'available_to' => Carbon::now()->addDays(30)->toDateString(),
            ],

            [
                'name' => 'Hyatt Regency Yogyakarta',
                'description' => 'Resor luas dengan lapangan golf dan pemandangan hijau.',
                'location' => 'Yogyakarta',
                'latitude' => -7.7470,
                'longitude' => 110.3617,
                'phone_number' => '0274888888',
                'facilities' => 'Lapangan golf, Kolam renang, Spa',
                'rating' => 4.8,
                'image_url' => 'https://www.ahstatic.com/photos/5451_ho_00_p_1024x768.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'available_from' => Carbon::now()->toDateString(),
                'available_to' => Carbon::now()->addDays(30)->toDateString(),
            ],

            [
                'name' => 'Royal Ambarrukmo Yogyakarta',
                'description' => 'Hotel mewah dengan sentuhan budaya Jawa.',
                'location' => 'Yogyakarta',
                'latitude' => -7.7823,
                'longitude' => 110.4086,
                'phone_number' => '0274581234',
                'facilities' => 'Pusat kebugaran, Kolam renang, Restoran',
                'rating' => 4.9,
                'image_url' => 'https://indonesia.tripcanvas.co/id/wp-content/uploads/sites/2/2020/11/10-1-Villa-Padi-by-@zidantourandtravel.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'available_from' => Carbon::now()->toDateString(),
                'available_to' => Carbon::now()->addDays(30)->toDateString(),
            ],
            [
                'name' => 'Melia Purosani Yogyakarta',
                'description' => 'Hotel bintang lima dengan fasilitas lengkap.',
                'location' => 'Yogyakarta',
                'latitude' => -7.7995,
                'longitude' => 110.3644,
                'phone_number' => '0274593210',
                'facilities' => 'Spa, Kolam renang, Restoran',
                'rating' => 4.6,
                'image_url' => 'https://photos.hotelbeds.com/giata/xxl/14/147212/147212a_hb_a_003.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'available_from' => Carbon::now()->toDateString(),
                'available_to' => Carbon::now()->addDays(30)->toDateString(),
            ],
            [
                'name' => 'Amaris Hotel Malioboro',
                'description' => 'Hotel budget dekat Malioboro.',
                'location' => 'Yogyakarta',
                'latitude' => -7.7924,
                'longitude' => 110.3653,
                'phone_number' => '02744567890',
                'facilities' => 'Wi-Fi gratis, Restoran, Parkir',
                'rating' => 4.3,
                'image_url' => 'https://media-cdn.tripadvisor.com/media/photo-s/0b/9d/cf/f6/sakanti-malioboro-hotel.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'available_from' => Carbon::now()->toDateString(),
                'available_to' => Carbon::now()->addDays(30)->toDateString(),
            ],
            [
                'name' => 'Hotel Tentrem Yogyakarta',
                'description' => 'Hotel mewah dengan fasilitas spa terbaik.',
                'location' => 'Yogyakarta',
                'latitude' => -7.7760,
                'longitude' => 110.3798,
                'phone_number' => '0274887766',
                'facilities' => 'Spa, Kolam renang, Gym',
                'rating' => 4.8,
                'image_url' => 'https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/t_htl-dskt/tix-hotel/images-web/2024/04/09/1eff650d-9128-4f45-a1dc-f14bf0b19890-1712624109455-abf7f33aa4495772f66fa854199033a3.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'available_from' => Carbon::now()->toDateString(),
                'available_to' => Carbon::now()->addDays(30)->toDateString(),
            ],
        ]);

        // Data Bali
        DB::table('pencarian')->insert([
            [
                'name' => 'Bali Villa with Garden View',
                'description' => 'Villa indah dengan pemandangan taman tropis.',
                'location' => 'Bali',
                'latitude' => -8.409518,
                'longitude' => 115.188919,
                'phone_number' => '08123456789',
                'facilities' => 'Kolam Renang, WiFi Gratis, Taman',
                'rating' => 4.9,
                'image_url' => 'https://pix8.agoda.net/hotelImages/1620545/-1/ace49be2413e71b6910fc66d3d9bf279.jpg?ca=16&ce=1&s=1024x',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'available_from' => Carbon::now()->toDateString(),
                'available_to' => Carbon::now()->addDays(30)->toDateString(),
            ],
            [
                'name' => 'Bali Beachfront Resort',
                'description' => 'Resort mewah dengan pemandangan pantai langsung.',
                'location' => 'Bali',
                'latitude' => -8.412345,
                'longitude' => 115.200123,
                'phone_number' => '08129876543',
                'facilities' => 'Pantai Pribadi, Kolam Renang Infinity, Spa',
                'rating' => 4.8,
                'image_url' => 'https://cf.bstatic.com/xdata/images/hotel/max1280x900/483592796.jpg?k=479ea8ec3f154a35c76e3e18f9b2d5297f1707c3dec3f5e0d7c72fe57fef6bee&o=&hp=1d6260702b86.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'available_from' => Carbon::now()->toDateString(),
                'available_to' => Carbon::now()->addDays(30)->toDateString(),
            ],
            [
                'name' => 'Bali Tropical Resort',
                'description' => 'Resort tropis dengan kamar luas dan pemandangan laut.',
                'location' => 'Bali',
                'latitude' => -8.421234,
                'longitude' => 115.201567,
                'phone_number' => '08134567890',
                'facilities' => 'Kolam Renang, Restoran, Spa',
                'rating' => 4.7,
                'image_url' => 'https://bdr.pphotels.com/application/sites/bdr/userfiles/gallery/hi-res/DSC09412.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'available_from' => Carbon::now()->toDateString(),
                'available_to' => Carbon::now()->addDays(30)->toDateString(),
            ],
            [
                'name' => 'Ubud Luxury Villa',
                'description' => 'Villa nyaman di Ubud dengan suasana tenang.',
                'location' => 'Bali',
                'latitude' => -8.500123,
                'longitude' => 115.273456,
                'phone_number' => '08127894567',
                'facilities' => 'Kolam Renang, WiFi Gratis, Sarapan',
                'rating' => 4.9,
                'image_url' => 'https://cf.bstatic.com/xdata/images/hotel/max1280x900/16879242.jpg?k=a946c5ad326f6eaf28635b9dcbec38d488526248a1dcc668217282c38f840b96&o=&hp=1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'available_from' => Carbon::now()->toDateString(),
                'available_to' => Carbon::now()->addDays(30)->toDateString(),
            ],
            [
                'name' => 'Bali Private Pool Villa',
                'description' => 'Villa eksklusif dengan kolam renang pribadi.',
                'location' => 'Bali',
                'latitude' => -8.409900,
                'longitude' => 115.222345,
                'phone_number' => '08124567890',
                'facilities' => 'Kolam Renang Pribadi, AC, Dapur Lengkap',
                'rating' => 4.8,
                'image_url' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/05/70/56/89/getlstd-property-photo.jpg?w=800&h=-1&s=1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'available_from' => Carbon::now()->toDateString(),
                'available_to' => Carbon::now()->addDays(30)->toDateString(),
            ],
            [
                'name' => 'Nusa Dua Water Villa',
                'description' => 'Villa indah dengan akses langsung ke air.',
                'location' => 'Bali',
                'latitude' => -8.800234,
                'longitude' => 115.225678,
                'phone_number' => '08125678901',
                'facilities' => 'Kolam Renang, Akses Air, Sarapan',
                'rating' => 4.8,
                'image_url' => 'https://cf.bstatic.com/xdata/images/hotel/max1280x900/291994082.jpg?k=0b4b1ad781f7c3bb8f491b0f2f3fabcc6b19c821330b1889d8c7767a1929822d&o=&hp=1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'available_from' => Carbon::now()->toDateString(),
                'available_to' => Carbon::now()->addDays(30)->toDateString(),
            ],
        ]);

        // Data Labuan Bajo
        DB::table('pencarian')->insert([
            [
                'name' => 'Labuan Bajo Beach Resort',
                'description' => 'Resor pantai dengan pemandangan Laut Flores.',
                'location' => 'Labuan Bajo',
                'latitude' => -8.4864,
                'longitude' => 119.8870,
                'phone_number' => '08123456789',
                'facilities' => 'Pantai Pribadi, Kolam Renang, Restoran',
                'rating' => 4.7,
                'image_url' => 'https://asset-2.tstatic.net/kupang/foto/bank/images/Ayana-Komodo-Resort-Sabtu-8-Oktober.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'available_from' => Carbon::now()->toDateString(),
                'available_to' => Carbon::now()->addDays(30)->toDateString(),
            ],
            [
                'name' => 'Labuan Bajo Luxury Villas',
                'description' => 'Vila mewah dengan kolam renang pribadi di Labuan Bajo.',
                'location' => 'Labuan Bajo',
                'latitude' => -8.4721,
                'longitude' => 119.8872,
                'phone_number' => '08129876543',
                'facilities' => 'Kolam Renang Pribadi, Spa, Taman',
                'rating' => 4.9,
                'image_url' => 'https://assets.promediateknologi.id/crop/0x0:0x0/750x500/webp/photo/2023/06/06/ando-vila-3106135805.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'available_from' => Carbon::now()->toDateString(),
                'available_to' => Carbon::now()->addDays(30)->toDateString(),
            ],
            [
                'name' => 'Komodo Dive Resort',
                'description' => 'Resor menyelam dengan akses langsung ke Pulau Komodo.',
                'location' => 'Labuan Bajo',
                'latitude' => -8.4315,
                'longitude' => 119.8907,
                'phone_number' => '08134567890',
                'facilities' => 'Menyelam, Kolam Renang, Restoran',
                'rating' => 4.8,
                'image_url' => 'https://discoveryourindonesia.com/wp-content/uploads/2016/09/Seraya-Hotel-and-Resort-Labuan-Bajo-Pool.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'available_from' => Carbon::now()->toDateString(),
                'available_to' => Carbon::now()->addDays(30)->toDateString(),
            ],
            [
                'name' => 'Labuan Bajo Eco Resort',
                'description' => 'Resor ramah lingkungan di Labuan Bajo dengan pemandangan alam.',
                'location' => 'Labuan Bajo',
                'latitude' => -8.4753,
                'longitude' => 119.8859,
                'phone_number' => '08127654321',
                'facilities' => 'Kolam Renang, Ekowisata, Restoran',
                'rating' => 4.6,
                'image_url' => 'https://cdn.idntimes.com/content-images/post/20200906/69596962-108495807074526-8285127339598007904-n-baa86383b029dd9adb2e81be9518c7eb.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'available_from' => Carbon::now()->toDateString(),
                'available_to' => Carbon::now()->addDays(30)->toDateString(),
            ],
            [
                'name' => 'Labuan Bajo Sunset View',
                'description' => 'Vila dengan pemandangan matahari terbenam yang indah.',
                'location' => 'Labuan Bajo',
                'latitude' => -8.4936,
                'longitude' => 119.8982,
                'phone_number' => '08125678901',
                'facilities' => 'Pemandangan Laut, Kolam Renang, Restoran',
                'rating' => 4.8,
                'image_url' => 'https://i.pinimg.com/originals/63/ee/73/63ee73f80e46b0ca864934c19fb86e8a.jpg',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
                'available_from' => Carbon::now()->toDateString(),
                'available_to' => Carbon::now()->addDays(30)->toDateString(),
            ],
        ]);

// Data Jakarta
DB::table('pencarian')->insert([
    [
        'name' => 'Hotel Mulia Senayan',
        'description' => 'Hotel mewah di pusat kota Jakarta.',
        'location' => 'Jakarta',
        'latitude' => -6.2261,
        'longitude' => 106.7914,
        'phone_number' => '02112345678',
        'facilities' => 'Kolam Renang, Spa, Restoran',
        'rating' => 4.9,
        'image_url' => 'https://asgam.com/wp-content/uploads/2018/07/International-Entertainment-768x458.jpg',
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
        'available_from' => Carbon::now()->toDateString(),
        'available_to' => Carbon::now()->addDays(30)->toDateString(),
    ],
    [
        'name' => 'Grand Hyatt Jakarta',
        'description' => 'Hotel bintang lima di pusat kota Jakarta.',
        'location' => 'Jakarta',
        'latitude' => -6.1959,
        'longitude' => 106.8221,
        'phone_number' => '02198765432',
        'facilities' => 'Pusat Kebugaran, Kolam Renang, Restoran',
        'rating' => 4.8,
        'image_url' => 'https://edge.media.datahc.com/HI362284026.jpg',
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
        'available_from' => Carbon::now()->toDateString(),
        'available_to' => Carbon::now()->addDays(30)->toDateString(),
    ],
    [
        'name' => 'The Ritz-Carlton Jakarta',
        'description' => 'Hotel mewah dengan layanan kelas dunia.',
        'location' => 'Jakarta',
        'latitude' => -6.2322,
        'longitude' => 106.8047,
        'phone_number' => '02123456789',
        'facilities' => 'Spa, Kolam Renang, Restoran',
        'rating' => 4.9,
        'image_url' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/21/40/3a/6a/hotel-facade.jpg?w=1200&h=-1&s=1',
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
        'available_from' => Carbon::now()->toDateString(),
        'available_to' => Carbon::now()->addDays(30)->toDateString(),
    ],
    [
        'name' => 'Shangri-La Hotel Jakarta',
        'description' => 'Hotel bintang lima dengan fasilitas lengkap.',
        'location' => 'Jakarta',
        'latitude' => -6.2356,
        'longitude' => 106.8225,
        'phone_number' => '0217654321',
        'facilities' => 'Spa, Kolam Renang, Pusat Kebugaran',
        'rating' => 4.8,
        'image_url' => 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/296671403.jpg?k=ef4d72db451d98b6fb70d8f42f255e08fed241cfe01bf5cc0e85bf930fc30478&o=&hp=1',
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
        'available_from' => Carbon::now()->toDateString(),
        'available_to' => Carbon::now()->addDays(30)->toDateString(),
    ],
    [
        'name' => 'Hotel Indonesia Kempinski Jakarta',
        'description' => 'Hotel ikonik di Jakarta dengan pemandangan kota.',
        'location' => 'Jakarta',
        'latitude' => -6.1945,
        'longitude' => 106.8220,
        'phone_number' => '02167890123',
        'facilities' => 'Kolam Renang, Restoran, Spa',
        'rating' => 4.9,
        'image_url' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/21/b7/80/04/hotel-building.jpg?w=700&h=-1&s=1',
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
        'available_from' => Carbon::now()->toDateString(),
        'available_to' => Carbon::now()->addDays(30)->toDateString(),
    ],
    [
        'name' => 'Four Seasons Hotel Jakarta',
        'description' => 'Hotel mewah dengan pemandangan kota Jakarta.',
        'location' => 'Jakarta',
        'latitude' => -6.2312,
        'longitude' => 106.8023,
        'phone_number' => '02198765432',
        'facilities' => 'Kolam Renang, Restoran, Spa',
        'rating' => 4.8,
        'image_url' => 'https://q-xx.bstatic.com/xdata/images/hotel/max1024x768/277734043.jpg?k=5947e5b69265307ea315e84851b5268f5215dfd3f7bfc44009c9f6f40e1e5851&o=',
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
        'available_from' => Carbon::now()->toDateString(),
        'available_to' => Carbon::now()->addDays(30)->toDateString(),

    ],

]);

    }
}
