<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Room;

class RoomSeeder extends Seeder
{
    public function run()
    {
        $rooms = [

            // Hotel The Phoenix Yogyakarta (ID 1)
            [
                'room_id' => 1,
                'pencarian_id' => 1,
                'room_number' => '101',
                'room_type' => 'Suite',
                'price_per_night' => 1500000, // Harga dalam Rupiah
                'facilities' => 'King Bed, Ocean View, Balcony',
                'image_url' => 'https://www.lottehotel.com/content/dam/lotte-hotel/lotte/seoul/accommodation/executive-tower/suite/presidential-suite-room/181026-49-2000-roo-LTSE.jpg.thumb.1920.1920.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 2,
                'pencarian_id' => 1,
                'room_number' => '102',
                'room_type' => 'Deluxe',
                'price_per_night' => 1200000,
                'facilities' => 'Queen Bed, Garden View',
                'image_url' => 'https://pix10.agoda.net/hotelImages/3008331/-1/5a32f6b96a79e9387bf046b2befc4def.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 3,
                'pencarian_id' => 1,
                'room_number' => '103',
                'room_type' => 'Standard',
                'price_per_night' => 900000,
                'facilities' => 'Double Bed, City View',
                'image_url' => 'https://dailyhotels.id/wp-content/uploads/2021/03/Standard-Room-e1617073694126.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Hyatt Regency Yogyakarta (ID 2)
            [
                'room_id' => 4,
                'pencarian_id' => 2,
                'room_number' => '201',
                'room_type' => 'Suite',
                'price_per_night' => 1800000,
                'facilities' => 'King Bed, Golf View, Balcony',
                'image_url' => 'https://www.lottehotel.com/content/dam/lotte-hotel/lotte/seoul/accommodation/executive-tower/suite/presidential-suite-room/181026-49-2000-roo-LTSE.jpg.thumb.1920.1920.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 5,
                'pencarian_id' => 2,
                'room_number' => '202',
                'room_type' => 'Deluxe',
                'price_per_night' => 1400000,
                'facilities' => 'Queen Bed, Pool View',
                'image_url' => 'https://pix10.agoda.net/hotelImages/3008331/-1/5a32f6b96a79e9387bf046b2befc4def.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 6,
                'pencarian_id' => 2,
                'room_number' => '203',
                'room_type' => 'Standard',
                'price_per_night' => 1100000,
                'facilities' => 'Double Bed, Garden View',
                'image_url' => 'https://dailyhotels.id/wp-content/uploads/2021/03/Standard-Room-e1617073694126.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Royal Ambarrukmo Yogyakarta (ID 3)
            [
                'room_id' => 7,
                'pencarian_id' => 3,
                'room_number' => '301',
                'room_type' => 'Suite',
                'price_per_night' => 1700000,
                'facilities' => 'King Bed, Heritage View',
                'image_url' => 'https://www.lottehotel.com/content/dam/lotte-hotel/lotte/seoul/accommodation/executive-tower/suite/presidential-suite-room/181026-49-2000-roo-LTSE.jpg.thumb.1920.1920.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 8,
                'pencarian_id' => 3,
                'room_number' => '302',
                'room_type' => 'Deluxe',
                'price_per_night' => 1300000,
                'facilities' => 'Queen Bed, City View',
                'image_url' => 'https://pix10.agoda.net/hotelImages/3008331/-1/5a32f6b96a79e9387bf046b2befc4def.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 9,
                'pencarian_id' => 3,
                'room_number' => '303',
                'room_type' => 'Standard',
                'price_per_night' => 1000000,
                'facilities' => 'Double Bed, Garden View',
                'image_url' => 'https://dailyhotels.id/wp-content/uploads/2021/03/Standard-Room-e1617073694126.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Melia Purosani Yogyakarta (ID 4)
            [
                'room_id' => 10,
                'pencarian_id' => 4,
                'room_number' => '401',
                'room_type' => 'Suite',
                'price_per_night' => 2000000,
                'facilities' => 'King Bed, Pool View, Spa Access',
                'image_url' => 'https://www.lottehotel.com/content/dam/lotte-hotel/lotte/seoul/accommodation/executive-tower/suite/presidential-suite-room/181026-49-2000-roo-LTSE.jpg.thumb.1920.1920.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 11,
                'pencarian_id' => 4,
                'room_number' => '402',
                'room_type' => 'Deluxe',
                'price_per_night' => 1500000,
                'facilities' => 'Queen Bed, Balcony View',
                'image_url' => 'https://pix10.agoda.net/hotelImages/3008331/-1/5a32f6b96a79e9387bf046b2befc4def.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_id' => 12,
                'pencarian_id' => 4,
                'room_number' => '403',
                'room_type' => 'Standard',
                'price_per_night' => 1200000,
                'facilities' => 'Double Bed, Garden View',
                'image_url' => 'https://dailyhotels.id/wp-content/uploads/2021/03/Standard-Room-e1617073694126.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
       // Amaris Hotel Malioboro (ID 5)
       [
        'room_id' => 13,
        'pencarian_id' => 5,
        'room_number' => '501',
        'room_type' => 'Suite',
        'price_per_night' => 1200000,
        'facilities' => 'King Bed, City View',
        'image_url' => 'https://www.lottehotel.com/content/dam/lotte-hotel/lotte/seoul/accommodation/executive-tower/suite/presidential-suite-room/181026-49-2000-roo-LTSE.jpg.thumb.1920.1920.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'room_id' => 14,
        'pencarian_id' => 5,
        'room_number' => '502',
        'room_type' => 'Deluxe',
        'price_per_night' => 1000000,
        'facilities' => 'Queen Bed, Garden View',
        'image_url' => 'https://pix10.agoda.net/hotelImages/3008331/-1/5a32f6b96a79e9387bf046b2befc4def.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'room_id' => 15,
        'pencarian_id' => 5,
        'room_number' => '503',
        'room_type' => 'Standard',
        'price_per_night' => 800000,
        'facilities' => 'Double Bed, Pool View',
        'image_url' => 'https://dailyhotels.id/wp-content/uploads/2021/03/Standard-Room-e1617073694126.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],

    // Hotel Tentrem Yogyakarta (ID 6)
    [
        'room_id' => 16,
        'pencarian_id' => 6,
        'room_number' => '601',
        'room_type' => 'Suite',
        'price_per_night' => 2500000,
        'facilities' => 'King Bed, Ocean View',
        'image_url' => 'https://www.lottehotel.com/content/dam/lotte-hotel/lotte/seoul/accommodation/executive-tower/suite/presidential-suite-room/181026-49-2000-roo-LTSE.jpg.thumb.1920.1920.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'room_id' => 17,
        'pencarian_id' => 6,
        'room_number' => '602',
        'room_type' => 'Deluxe',
        'price_per_night' => 1800000,
        'facilities' => 'Queen Bed, Garden View',
        'image_url' => 'https://pix10.agoda.net/hotelImages/3008331/-1/5a32f6b96a79e9387bf046b2befc4def.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'room_id' => 18,
        'pencarian_id' => 6,
        'room_number' => '603',
        'room_type' => 'Standard',
        'price_per_night' => 1500000,
        'facilities' => 'Double Bed, City View',
        'image_url' => 'https://dailyhotels.id/wp-content/uploads/2021/03/Standard-Room-e1617073694126.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],

    // Bali Villa with Garden View (ID 7)
    [
        'room_id' => 19,
        'pencarian_id' => 7,
        'room_number' => '701',
        'room_type' => 'Suite',
        'price_per_night' => 3000000,
        'facilities' => 'King Bed, Garden View',
        'image_url' => 'https://www.lottehotel.com/content/dam/lotte-hotel/lotte/seoul/accommodation/executive-tower/suite/presidential-suite-room/181026-49-2000-roo-LTSE.jpg.thumb.1920.1920.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'room_id' => 20,
        'pencarian_id' => 7,
        'room_number' => '702',
        'room_type' => 'Deluxe',
        'price_per_night' => 2000000,
        'facilities' => 'Queen Bed, Pool View',
        'image_url' => 'https://pix10.agoda.net/hotelImages/3008331/-1/5a32f6b96a79e9387bf046b2befc4def.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'room_id' => 21,
        'pencarian_id' => 7,
        'room_number' => '703',
        'room_type' => 'Standard',
        'price_per_night' => 1500000,
        'facilities' => 'Double Bed, Garden View',
        'image_url' => 'https://dailyhotels.id/wp-content/uploads/2021/03/Standard-Room-e1617073694126.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
     // Bali Private Pool Villa (ID 8)
     [
        'room_id' => 22,
        'pencarian_id' => 8,
        'room_number' => '801',
        'room_type' => 'Suite',
        'price_per_night' => 3500000,
        'facilities' => 'King Bed, Private Pool, Garden View',
        'image_url' => 'https://png.pngtree.com/thumb_back/fw800/background/20230722/pngtree-a-luxurious-hotel-bedroom-suite-featuring-a-3d-rendering-with-a-image_3711432.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'room_id' => 23,
        'pencarian_id' => 8,
        'room_number' => '802',
        'room_type' => 'Deluxe',
        'price_per_night' => 2500000,
        'facilities' => 'Queen Bed, Balcony View',
        'image_url' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/05/70/56/89/getlstd-property-photo.jpg?w=800&h=-1&s=1',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'room_id' => 24,
        'pencarian_id' => 8,
        'room_number' => '803',
        'room_type' => 'Standard',
        'price_per_night' => 1800000,
        'facilities' => 'Double Bed, City View',
        'image_url' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/05/70/56/89/getlstd-property-photo.jpg?w=800&h=-1&s=1',
        'created_at' => now(),
        'updated_at' => now(),
    ],

    // Nusa Dua Water Villa (ID 9)
    [
        'room_id' => 25,
        'pencarian_id' => 9,
        'room_number' => '901',
        'room_type' => 'Suite',
        'price_per_night' => 4000000,
        'facilities' => 'King Bed, Ocean View, Private Deck',
        'image_url' => 'https://png.pngtree.com/thumb_back/fw800/background/20230722/pngtree-a-luxurious-hotel-bedroom-suite-featuring-a-3d-rendering-with-a-image_3711432.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'room_id' => 26,
        'pencarian_id' => 9,
        'room_number' => '902',
        'room_type' => 'Deluxe',
        'price_per_night' => 3000000,
        'facilities' => 'Queen Bed, Pool View',
        'image_url' => 'https://cf.bstatic.com/xdata/images/hotel/max1280x900/291994082.jpg?k=0b4b1ad781f7c3bb8f491b0f2f3fabcc6b19c821330b1889d8c7767a1929822d&o=&hp=1',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'room_id' => 27,
        'pencarian_id' => 9,
        'room_number' => '903',
        'room_type' => 'Standard',
        'price_per_night' => 2200000,
        'facilities' => 'Double Bed, Garden View',
        'image_url' => 'https://cf.bstatic.com/xdata/images/hotel/max1280x900/291994082.jpg?k=0b4b1ad781f7c3bb8f491b0f2f3fabcc6b19c821330b1889d8c7767a1929822d&o=&hp=1',
        'created_at' => now(),
        'updated_at' => now(),
    ],
     // Bali Tropical Resort (ID 10)
     [
        'room_id' => 28,
        'pencarian_id' => 10,
        'room_number' => '1001',
        'room_type' => 'Suite',
        'price_per_night' => 3800000,
        'facilities' => 'King Bed, Ocean View, Private Balcony',
        'image_url' => 'https://png.pngtree.com/thumb_back/fw800/background/20230722/pngtree-a-luxurious-hotel-bedroom-suite-featuring-a-3d-rendering-with-a-image_3711432.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'room_id' => 29,
        'pencarian_id' => 10,
        'room_number' => '1002',
        'room_type' => 'Deluxe',
        'price_per_night' => 2800000,
        'facilities' => 'Queen Bed, Garden View, Wi-Fi',
        'image_url' => 'https://pix10.agoda.net/hotelImages/3008331/-1/5a32f6b96a79e9387bf046b2befc4def.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'room_id' => 30,
        'pencarian_id' => 10,
        'room_number' => '1003',
        'room_type' => 'Standard',
        'price_per_night' => 1800000,
        'facilities' => 'Double Bed, City View',
        'image_url' => 'https://dailyhotels.id/wp-content/uploads/2021/03/Standard-Room-e1617073694126.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],

    // Ubud Luxury Villa (ID 11)
    [
        'room_id' => 31,
        'pencarian_id' => 11,
        'room_number' => '1101',
        'room_type' => 'Suite',
        'price_per_night' => 5000000,
        'facilities' => 'King Bed, Private Pool, Mountain View',
        'image_url' => 'https://png.pngtree.com/thumb_back/fw800/background/20230722/pngtree-a-luxurious-hotel-bedroom-suite-featuring-a-3d-rendering-with-a-image_3711432.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'room_id' => 32,
        'pencarian_id' => 11,
        'room_number' => '1102',
        'room_type' => 'Deluxe',
        'price_per_night' => 3200000,
        'facilities' => 'Queen Bed, Garden View',
        'image_url' => 'https://pix10.agoda.net/hotelImages/3008331/-1/5a32f6b96a79e9387bf046b2befc4def.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'room_id' => 33,
        'pencarian_id' => 11,
        'room_number' => '1103',
        'room_type' => 'Standard',
        'price_per_night' => 2500000,
        'facilities' => 'Double Bed, Forest View',
        'image_url' => 'https://dailyhotels.id/wp-content/uploads/2021/03/Standard-Room-e1617073694126.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],

    // Bali Private Pool Villa (ID 12)
    [
        'room_id' => 34,
        'pencarian_id' => 12,
        'room_number' => '1201',
        'room_type' => 'Suite',
        'price_per_night' => 6000000,
        'facilities' => 'King Bed, Private Pool, Spa Access',
        'image_url' => 'https://png.pngtree.com/thumb_back/fw800/background/20230722/pngtree-a-luxurious-hotel-bedroom-suite-featuring-a-3d-rendering-with-a-image_3711432.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'room_id' => 35,
        'pencarian_id' => 12,
        'room_number' => '1202',
        'room_type' => 'Deluxe',
        'price_per_night' => 3500000,
        'facilities' => 'Queen Bed, Pool View',
        'image_url' => 'https://pix10.agoda.net/hotelImages/3008331/-1/5a32f6b96a79e9387bf046b2befc4def.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'room_id' => 36,
        'pencarian_id' => 12,
        'room_number' => '1203',
        'room_type' => 'Standard',
        'price_per_night' => 2700000,
        'facilities' => 'Double Bed, Garden View',
        'image_url' => 'https://dailyhotels.id/wp-content/uploads/2021/03/Standard-Room-e1617073694126.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    // Labuan Bajo Beach Resort (ID 13)
    [
        'room_id' => 37,
        'pencarian_id' => 13,
        'room_number' => '1301',
        'room_type' => 'Suite',
        'price_per_night' => 4500000,
        'facilities' => 'King Bed, Ocean View, Private Balcony',
        'image_url' => 'https://png.pngtree.com/thumb_back/fw800/background/20230722/pngtree-a-luxurious-hotel-bedroom-suite-featuring-a-3d-rendering-with-a-image_3711432.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'room_id' => 38,
        'pencarian_id' => 13,
        'room_number' => '1302',
        'room_type' => 'Deluxe',
        'price_per_night' => 3200000,
        'facilities' => 'Queen Bed, Pool View',
        'image_url' => 'https://pix10.agoda.net/hotelImages/3008331/-1/5a32f6b96a79e9387bf046b2befc4def.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'room_id' => 39,
        'pencarian_id' => 13,
        'room_number' => '1303',
        'room_type' => 'Standard',
        'price_per_night' => 2500000,
        'facilities' => 'Double Bed, Garden View',
        'image_url' => 'https://dailyhotels.id/wp-content/uploads/2021/03/Standard-Room-e1617073694126.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],

    // Labuan Bajo Luxury Villas (ID 14)
    [
        'room_id' => 40,
        'pencarian_id' => 14,
        'room_number' => '1401',
        'room_type' => 'Suite',
        'price_per_night' => 7000000,
        'facilities' => 'King Bed, Private Pool, Ocean View',
        'image_url' => 'https://png.pngtree.com/thumb_back/fw800/background/20230722/pngtree-a-luxurious-hotel-bedroom-suite-featuring-a-3d-rendering-with-a-image_3711432.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'room_id' => 41,
        'pencarian_id' => 14,
        'room_number' => '1402',
        'room_type' => 'Deluxe',
        'price_per_night' => 5000000,
        'facilities' => 'Queen Bed, Balcony View',
        'image_url' => 'https://pix10.agoda.net/hotelImages/3008331/-1/5a32f6b96a79e9387bf046b2befc4def.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'room_id' => 42,
        'pencarian_id' => 14,
        'room_number' => '1403',
        'room_type' => 'Standard',
        'price_per_night' => 3500000,
        'facilities' => 'Double Bed, Garden View',
        'image_url' => 'https://dailyhotels.id/wp-content/uploads/2021/03/Standard-Room-e1617073694126.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],

    // Komodo Dive Resort (ID 15)
    [
        'room_id' => 43,
        'pencarian_id' => 15,
        'room_number' => '1501',
        'room_type' => 'Suite',
        'price_per_night' => 6000000,
        'facilities' => 'King Bed, Diving Access, Ocean View',
        'image_url' => 'https://png.pngtree.com/thumb_back/fw800/background/20230722/pngtree-a-luxurious-hotel-bedroom-suite-featuring-a-3d-rendering-with-a-image_3711432.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'room_id' => 44,
        'pencarian_id' => 15,
        'room_number' => '1502',
        'room_type' => 'Deluxe',
        'price_per_night' => 4500000,
        'facilities' => 'Queen Bed, Pool View',
        'image_url' => 'https://pix10.agoda.net/hotelImages/3008331/-1/5a32f6b96a79e9387bf046b2befc4def.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'room_id' => 45,
        'pencarian_id' => 15,
        'room_number' => '1503',
        'room_type' => 'Standard',
        'price_per_night' => 3200000,
        'facilities' => 'Double Bed, Garden View',
        'image_url' => 'https://dailyhotels.id/wp-content/uploads/2021/03/Standard-Room-e1617073694126.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
     // Labuan Bajo Eco Resort (ID 16)
     [
        'room_id' => 46,
        'pencarian_id' => 16,
        'room_number' => '1601',
        'room_type' => 'Suite',
        'price_per_night' => 5000000,
        'facilities' => 'King Bed, Eco View, Private Balcony',
        'image_url' => 'https://png.pngtree.com/thumb_back/fw800/background/20230722/pngtree-a-luxurious-hotel-bedroom-suite-featuring-a-3d-rendering-with-a-image_3711432.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'room_id' => 47,
        'pencarian_id' => 16,
        'room_number' => '1602',
        'room_type' => 'Deluxe',
        'price_per_night' => 3500000,
        'facilities' => 'Queen Bed, Eco View',
        'image_url' => 'https://pix10.agoda.net/hotelImages/3008331/-1/5a32f6b96a79e9387bf046b2befc4def.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'room_id' => 48,
        'pencarian_id' => 16,
        'room_number' => '1603',
        'room_type' => 'Standard',
        'price_per_night' => 2500000,
        'facilities' => 'Double Bed, Eco View',
        'image_url' => 'https://dailyhotels.id/wp-content/uploads/2021/03/Standard-Room-e1617073694126.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],

    // Labuan Bajo Sunset View (ID 17)
    [
        'room_id' => 49,
        'pencarian_id' => 17,
        'room_number' => '1701',
        'room_type' => 'Suite',
        'price_per_night' => 6000000,
        'facilities' => 'King Bed, Ocean Sunset View',
        'image_url' => 'https://png.pngtree.com/thumb_back/fw800/background/20230722/pngtree-a-luxurious-hotel-bedroom-suite-featuring-a-3d-rendering-with-a-image_3711432.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'room_id' => 50,
        'pencarian_id' => 17,
        'room_number' => '1702',
        'room_type' => 'Deluxe',
        'price_per_night' => 4000000,
        'facilities' => 'Queen Bed, Balcony Sunset View',
        'image_url' => 'https://pix10.agoda.net/hotelImages/3008331/-1/5a32f6b96a79e9387bf046b2befc4def.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'room_id' => 51,
        'pencarian_id' => 17,
        'room_number' => '1703',
        'room_type' => 'Standard',
        'price_per_night' => 3000000,
        'facilities' => 'Double Bed, Garden Sunset View',
        'image_url' => 'https://dailyhotels.id/wp-content/uploads/2021/03/Standard-Room-e1617073694126.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],

    // Hotel Mulia Senayan (ID 18)
    [
        'room_id' => 52,
        'pencarian_id' => 18,
        'room_number' => '1801',
        'room_type' => 'Suite',
        'price_per_night' => 7500000,
        'facilities' => 'King Bed, City Skyline View',
        'image_url' => 'https://png.pngtree.com/thumb_back/fw800/background/20230722/pngtree-a-luxurious-hotel-bedroom-suite-featuring-a-3d-rendering-with-a-image_3711432.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'room_id' => 53,
        'pencarian_id' => 18,
        'room_number' => '1802',
        'room_type' => 'Deluxe',
        'price_per_night' => 5000000,
        'facilities' => 'Queen Bed, Skyline View',
        'image_url' => 'https://pix10.agoda.net/hotelImages/3008331/-1/5a32f6b96a79e9387bf046b2befc4def.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'room_id' => 54,
        'pencarian_id' => 18,
        'room_number' => '1803',
        'room_type' => 'Standard',
        'price_per_night' => 4000000,
        'facilities' => 'Double Bed, City View',
        'image_url' => 'https://dailyhotels.id/wp-content/uploads/2021/03/Standard-Room-e1617073694126.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
     // Grand Hyatt Jakarta (ID 19)
     [
        'room_id' => 55,
        'pencarian_id' => 19,
        'room_number' => '1901',
        'room_type' => 'Suite',
        'price_per_night' => 9000000,
        'facilities' => 'King Bed, Skyline View, Private Balcony',
        'image_url' => 'https://png.pngtree.com/thumb_back/fw800/background/20230722/pngtree-a-luxurious-hotel-bedroom-suite-featuring-a-3d-rendering-with-a-image_3711432.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'room_id' => 56,
        'pencarian_id' => 19,
        'room_number' => '1902',
        'room_type' => 'Deluxe',
        'price_per_night' => 7000000,
        'facilities' => 'Queen Bed, City View',
        'image_url' => 'https://pix10.agoda.net/hotelImages/3008331/-1/5a32f6b96a79e9387bf046b2befc4def.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'room_id' => 57,
        'pencarian_id' => 19,
        'room_number' => '1903',
        'room_type' => 'Standard',
        'price_per_night' => 5000000,
        'facilities' => 'Double Bed, Garden View',
        'image_url' => 'https://dailyhotels.id/wp-content/uploads/2021/03/Standard-Room-e1617073694126.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],

    // The Ritz-Carlton Jakarta (ID 20)
    [
        'room_id' => 58,
        'pencarian_id' => 20,
        'room_number' => '2001',
        'room_type' => 'Suite',
        'price_per_night' => 10000000,
        'facilities' => 'King Bed, City Skyline View, Jacuzzi',
        'image_url' => 'https://png.pngtree.com/thumb_back/fw800/background/20230722/pngtree-a-luxurious-hotel-bedroom-suite-featuring-a-3d-rendering-with-a-image_3711432.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'room_id' => 59,
        'pencarian_id' => 20,
        'room_number' => '2002',
        'room_type' => 'Deluxe',
        'price_per_night' => 7500000,
        'facilities' => 'Queen Bed, City View',
        'image_url' => 'https://pix10.agoda.net/hotelImages/3008331/-1/5a32f6b96a79e9387bf046b2befc4def.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'room_id' => 60,
        'pencarian_id' => 20,
        'room_number' => '2003',
        'room_type' => 'Standard',
        'price_per_night' => 6000000,
        'facilities' => 'Double Bed, Garden View',
        'image_url' => 'https://dailyhotels.id/wp-content/uploads/2021/03/Standard-Room-e1617073694126.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],

    // Shangri-La Hotel Jakarta (ID 21)
    [
        'room_id' => 61,
        'pencarian_id' => 21,
        'room_number' => '2101',
        'room_type' => 'Suite',
        'price_per_night' => 9500000,
        'facilities' => 'King Bed, Pool View, Private Balcony',
        'image_url' => 'https://png.pngtree.com/thumb_back/fw800/background/20230722/pngtree-a-luxurious-hotel-bedroom-suite-featuring-a-3d-rendering-with-a-image_3711432.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'room_id' => 62,
        'pencarian_id' => 21,
        'room_number' => '2102',
        'room_type' => 'Deluxe',
        'price_per_night' => 7000000,
        'facilities' => 'Queen Bed, Pool View',
        'image_url' => 'https://pix10.agoda.net/hotelImages/3008331/-1/5a32f6b96a79e9387bf046b2befc4def.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'room_id' => 63,
        'pencarian_id' => 21,
        'room_number' => '2103',
        'room_type' => 'Standard',
        'price_per_night' => 5000000,
        'facilities' => 'Double Bed, City View',
        'image_url' => 'https://dailyhotels.id/wp-content/uploads/2021/03/Standard-Room-e1617073694126.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    // Data Jakarta: Hotel Indonesia Kempinski Jakarta (pencarian_id = 20)
    [
        'room_id' => 64,
        'pencarian_id' => 22,
        'room_number' => '1201',
        'room_type' => 'Suite',
        'price_per_night' => 3500000,
        'facilities' => 'King Bed, City View, Private Lounge',
        'image_url' => 'https://png.pngtree.com/thumb_back/fw800/background/20230722/pngtree-a-luxurious-hotel-bedroom-suite-featuring-a-3d-rendering-with-a-image_3711432.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'room_id' => 65,
        'pencarian_id' => 22,
        'room_number' => '1202',
        'room_type' => 'Deluxe',
        'price_per_night' => 2200000,
        'facilities' => 'Queen Bed, Pool View',
        'image_url' => 'https://pix10.agoda.net/hotelImages/3008331/-1/5a32f6b96a79e9387bf046b2befc4def.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'room_id' => 66,
        'pencarian_id' => 22,
        'room_number' => '1203',
        'room_type' => 'Standard',
        'price_per_night' => 1500000,
        'facilities' => 'Double Bed, Garden View',
        'image_url' => 'https://dailyhotels.id/wp-content/uploads/2021/03/Standard-Room-e1617073694126.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],

    // Data Jakarta: Four Seasons Hotel Jakarta (pencarian_id = 21)
    [
        'room_id' => 67,
        'pencarian_id' => 23,
        'room_number' => '1301',
        'room_type' => 'Suite',
        'price_per_night' => 4000000,
        'facilities' => 'King Bed, City View, Private Lounge',
        'image_url' => 'https://png.pngtree.com/thumb_back/fw800/background/20230722/pngtree-a-luxurious-hotel-bedroom-suite-featuring-a-3d-rendering-with-a-image_3711432.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'room_id' => 68,
        'pencarian_id' => 23,
        'room_number' => '1302',
        'room_type' => 'Deluxe',
        'price_per_night' => 2500000,
        'facilities' => 'Queen Bed, Pool View',
        'image_url' => 'https://pix10.agoda.net/hotelImages/3008331/-1/5a32f6b96a79e9387bf046b2befc4def.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'room_id' => 69,
        'pencarian_id' => 23,
        'room_number' => '1303',
        'room_type' => 'Standard',
        'price_per_night' => 1800000,
        'facilities' => 'Double Bed, City View',
        'image_url' => 'https://dailyhotels.id/wp-content/uploads/2021/03/Standard-Room-e1617073694126.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],

];

// Insert data kamar ke database
Room::insert($rooms);
}
}

